name: Auto tag

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'AGENTS.md'
      - '**/*.md'

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Test
        run: go test ./...
      - name: Bump version and push tag
        if: ${{ success() }}
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
